Insert into Candidates values('Michael','Scott',30)
Insert into Candidates values('Andy','Bernard',30)
Insert into Candidates values('Deangelo','Vickers',30)
Insert into Candidates values('Dwight','Schrute',30)
Insert into Candidates values('John','Halpert',30)
Insert into Candidates values('Pam','Beasly',30)
Insert into Candidates values('Erin','Hannon',30)
Insert into Candidates values('Kevin','Malone',30)

Insert into Voters values('Michael','Scott',30)
Insert into Voters values('Andy','Bernard',30)
Insert into Voters values('Deangelo','Vickers',30)
Insert into Voters values('Dwight','Schrute',30)
Insert into Voters values('John','Halpert',30)
Insert into Voters values('Pam','Beasly',30)
Insert into Voters values('Erin','Hannon',30)
Insert into Voters values('Kevin','Malone',30)
Insert into Voters values('Manideep','Yechuri',28)
Insert into Voters values('Timo','Baker',30)
Insert into Voters values('Andrew','Tye',30)
Insert into Voters values('Mike','Scott',30)
Insert into Voters values('Edward','Johnson',30)
Insert into Voters values('Adam','Taylor',30)
Insert into Voters values('Mark','stevenson',30)

Insert into Category values('President')
Insert into Category values('Vice President')
Insert into Category values('Secretary')


Insert into Candidate values(1,1)
Insert into Candidate values(1,2)
Insert into Candidate values(1,3)
Insert into Candidate values(2,4)
Insert into Candidate values(2,5)
Insert into Candidate values(3,6)
Insert into Candidate values(3,7)
Insert into Candidate values(3,8)

Insert into Vote values(9,1,1,1)
Insert into Vote values(9,4,2,4)
Insert into Vote values(9,6,3,6)
